vich_uploader:
    db_driver: orm

    mappings:
        user_contracts:
            uri_prefix: '%app.path.user_contracts%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_contracts%'
